/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreSetupRouteImport } from './routes/store-setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMissionsIndexRouteImport } from './routes/_authenticated/missions/index'
import { Route as AuthenticatedMissionsCreateRouteImport } from './routes/_authenticated/missions/create'
import { Route as AuthenticatedMissionsMissionIdRouteImport } from './routes/_authenticated/missions/$missionId'
import { Route as AuthenticatedMissionsMissionIdEditRouteImport } from './routes/_authenticated/missions/$missionId.edit'

const StoreSetupRoute = StoreSetupRouteImport.update({
  id: '/store-setup',
  path: '/store-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMissionsIndexRoute =
  AuthenticatedMissionsIndexRouteImport.update({
    id: '/missions/',
    path: '/missions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsCreateRoute =
  AuthenticatedMissionsCreateRouteImport.update({
    id: '/missions/create',
    path: '/missions/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsMissionIdRoute =
  AuthenticatedMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMissionsMissionIdEditRoute =
  AuthenticatedMissionsMissionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedMissionsMissionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/store-setup': typeof StoreSetupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/store': typeof AuthenticatedStoreRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/missions/create': typeof AuthenticatedMissionsCreateRoute
  '/missions/': typeof AuthenticatedMissionsIndexRoute
  '/missions/$missionId/edit': typeof AuthenticatedMissionsMissionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/store-setup': typeof StoreSetupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/store': typeof AuthenticatedStoreRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/missions/create': typeof AuthenticatedMissionsCreateRoute
  '/missions': typeof AuthenticatedMissionsIndexRoute
  '/missions/$missionId/edit': typeof AuthenticatedMissionsMissionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/store-setup': typeof StoreSetupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/missions/$missionId': typeof AuthenticatedMissionsMissionIdRouteWithChildren
  '/_authenticated/missions/create': typeof AuthenticatedMissionsCreateRoute
  '/_authenticated/missions/': typeof AuthenticatedMissionsIndexRoute
  '/_authenticated/missions/$missionId/edit': typeof AuthenticatedMissionsMissionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/store-setup'
    | '/dashboard'
    | '/store'
    | '/missions/$missionId'
    | '/missions/create'
    | '/missions/'
    | '/missions/$missionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/store-setup'
    | '/dashboard'
    | '/store'
    | '/missions/$missionId'
    | '/missions/create'
    | '/missions'
    | '/missions/$missionId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/store-setup'
    | '/_authenticated/dashboard'
    | '/_authenticated/store'
    | '/_authenticated/missions/$missionId'
    | '/_authenticated/missions/create'
    | '/_authenticated/missions/'
    | '/_authenticated/missions/$missionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StoreSetupRoute: typeof StoreSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store-setup': {
      id: '/store-setup'
      path: '/store-setup'
      fullPath: '/store-setup'
      preLoaderRoute: typeof StoreSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions/': {
      id: '/_authenticated/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof AuthenticatedMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions/create': {
      id: '/_authenticated/missions/create'
      path: '/missions/create'
      fullPath: '/missions/create'
      preLoaderRoute: typeof AuthenticatedMissionsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions/$missionId': {
      id: '/_authenticated/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/missions/$missionId/edit': {
      id: '/_authenticated/missions/$missionId/edit'
      path: '/edit'
      fullPath: '/missions/$missionId/edit'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdEditRouteImport
      parentRoute: typeof AuthenticatedMissionsMissionIdRoute
    }
  }
}

interface AuthenticatedMissionsMissionIdRouteChildren {
  AuthenticatedMissionsMissionIdEditRoute: typeof AuthenticatedMissionsMissionIdEditRoute
}

const AuthenticatedMissionsMissionIdRouteChildren: AuthenticatedMissionsMissionIdRouteChildren =
  {
    AuthenticatedMissionsMissionIdEditRoute:
      AuthenticatedMissionsMissionIdEditRoute,
  }

const AuthenticatedMissionsMissionIdRouteWithChildren =
  AuthenticatedMissionsMissionIdRoute._addFileChildren(
    AuthenticatedMissionsMissionIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedMissionsMissionIdRoute: typeof AuthenticatedMissionsMissionIdRouteWithChildren
  AuthenticatedMissionsCreateRoute: typeof AuthenticatedMissionsCreateRoute
  AuthenticatedMissionsIndexRoute: typeof AuthenticatedMissionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedMissionsMissionIdRoute:
    AuthenticatedMissionsMissionIdRouteWithChildren,
  AuthenticatedMissionsCreateRoute: AuthenticatedMissionsCreateRoute,
  AuthenticatedMissionsIndexRoute: AuthenticatedMissionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StoreSetupRoute: StoreSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
